backend:
  batch_size: 50
  batch_size_reduction: 'True'
  batch_size_reduction_factor: 2
  display_step: 50
  evaluator: tensorpot
  gpu_config:
    mem_limit: 0
cutoff: 6
data:
  filename: /Users/dft-dutoit/Documents/xpot/examples/cu_icams.pckl.gzip
  test_size: 0.1
fit:
  loss:
    L1_coeffs: 1.0e-08
    L2_coeffs: 1.0e-08
    kappa: auto
    w0_rad: 1.0e-08
    w1_coeffs: 0
    w1_rad: 1.0e-08
    w2_coeffs: 0
    w2_rad: 1.0e-08
  maxiter: 10
  optimizer: BFGS
  repulsion: auto
  trainable_parameters: ALL
metadata:
  purpose: Potential fit
potential:
  bonds:
    ALL:
      NameofCutoffFunction: cos
      dcut: 0.060088165636702225
      radbase: SBessel
      radparameters:
      - 2.6509131087954745
      rcut: 5.339073000818308
  deltaSplineBins: 0.001
  elements:
  - Cu
  embeddings:
    ALL:
      drho_core_cut: 500
      fs_parameters:
      - 1
      - 1
      - 1
      - 1.6134316750344428
      ndensity: 2
      npot: FinnisSinclairShiftedScaled
      rho_core_cut: 3000
  functions:
    ALL:
      lmax_by_orders:
      - 0
      - 4
      - 3
      - 2
      - 1
      - 0
      nradmax_by_orders:
      - 15
      - 6
      - 4
      - 3
      - 2
      - 2
    number_of_functions_per_element: 50
seed: 42
